"""add provider field to video_projects

Revision ID: 182ef49c0f06
Revises: 
Create Date: 2026-03-03 12:08:29.606525
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182ef49c0f06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_projects',
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SCRIPT_GENERATING', 'AUDIO_GENERATING', 'VIDEO_GENERATING', 'ASSEMBLING', 'UPLOADING', 'COMPLETED', 'FAILED', name='video_status', create_constraint=True), nullable=False),
    sa.Column('format', sa.Enum('SHORT', 'LONG', name='video_format', create_constraint=True), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='LLM provider used: openai or anthropic'),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('audio_path', sa.String(length=1024), nullable=True),
    sa.Column('video_path', sa.String(length=1024), nullable=True),
    sa.Column('output_path', sa.String(length=1024), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=64), nullable=True),
    sa.Column('youtube_url', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_projects')
    # ### end Alembic commands ###
