"""add telegram integration

Revision ID: 2570d3ae3726
Revises: f6c0d6f1328b
Create Date: 2026-03-03 12:50:47.342917
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2570d3ae3726'
down_revision: Union[str, None] = 'f6c0d6f1328b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Telegram user ID'),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('is_allowed', sa.Boolean(), nullable=False, comment='Whether user is in allowlist'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Admin users bypass rate limits'),
    sa.Column('videos_this_hour', sa.Integer(), nullable=False),
    sa.Column('rate_limit_reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_videos_requested', sa.Integer(), nullable=False),
    sa.Column('last_command_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_telegram_users_is_allowed'), 'telegram_users', ['is_allowed'], unique=False)
    op.add_column('video_projects', sa.Column('telegram_user_id', sa.BigInteger(), nullable=True, comment='Telegram user ID who requested this video'))
    op.add_column('video_projects', sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True, comment='Telegram chat ID where video was requested'))
    op.add_column('video_projects', sa.Column('telegram_message_id', sa.Integer(), nullable=True, comment='Telegram message ID to edit with status updates'))
    op.create_index(op.f('ix_video_projects_telegram_user_id'), 'video_projects', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_projects_telegram_user_id'), table_name='video_projects')
    op.drop_column('video_projects', 'telegram_message_id')
    op.drop_column('video_projects', 'telegram_chat_id')
    op.drop_column('video_projects', 'telegram_user_id')
    op.drop_index(op.f('ix_telegram_users_is_allowed'), table_name='telegram_users')
    op.drop_table('telegram_users')
    # ### end Alembic commands ###
