"""sync_comments_indexes_and_cleanup_enum

Revision ID: 3967a5f94766
Revises: a1b2c3d4e5f6
Create Date: 2026-03-11 21:29:40.240219
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3967a5f94766'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── Clean up duplicate 'scene_splitting' enum value ──────────
    # The enum has both 'scene_splitting' (lowercase, added by migration d1e2f3a4b5c6)
    # and 'SCENE_SPLITTING' (uppercase). The ORM uses 'SCENE_SPLITTING'.
    # PostgreSQL doesn't support DROP VALUE, so we rename the lowercase one
    # by replacing the enum type entirely.
    op.execute("""
        ALTER TYPE video_status RENAME TO video_status_old;

        CREATE TYPE video_status AS ENUM (
            'PENDING', 'SCRIPT_GENERATING', 'SCENE_SPLITTING',
            'AUDIO_GENERATING', 'VIDEO_GENERATING',
            'ASSEMBLING', 'UPLOADING', 'COMPLETED', 'FAILED'
        );

        ALTER TABLE video_projects
            ALTER COLUMN status TYPE video_status
            USING status::text::video_status;

        DROP TYPE video_status_old;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_patterns', 'pattern_type',
               existing_type=sa.VARCHAR(length=50),
               comment='hook_style, topic, cta, script_structure, length',
               existing_nullable=False)
    op.alter_column('performance_patterns', 'description',
               existing_type=sa.TEXT(),
               comment='Human-readable pattern description',
               existing_nullable=False)
    op.alter_column('performance_patterns', 'pattern_data',
               existing_type=sa.TEXT(),
               comment='JSON structured pattern details',
               existing_nullable=False)
    op.alter_column('performance_patterns', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='0.0 to 1.0',
               existing_nullable=False)
    op.alter_column('performance_patterns', 'sample_size',
               existing_type=sa.INTEGER(),
               comment='Number of videos this pattern is based on',
               existing_nullable=False)
    op.alter_column('performance_patterns', 'avg_views',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Average views for videos matching this pattern',
               existing_nullable=False)
    op.alter_column('performance_patterns', 'avg_retention',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Average retention percentage',
               existing_nullable=True)
    op.alter_column('performance_patterns', 'supporting_evidence',
               existing_type=sa.TEXT(),
               comment='JSON list of project_ids and their stats',
               existing_nullable=False)
    op.alter_column('prompt_versions', 'version_label',
               existing_type=sa.VARCHAR(length=100),
               comment='v1, v2.1, experiment-hooks-q3',
               existing_nullable=False)
    op.alter_column('prompt_versions', 'template',
               existing_type=sa.TEXT(),
               comment='Full prompt template with {placeholders}',
               existing_nullable=False)
    op.alter_column('prompt_versions', 'variables',
               existing_type=sa.TEXT(),
               comment='JSON default variable values',
               existing_nullable=True)
    op.alter_column('prompt_versions', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Currently in use (only one active at a time)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('prompt_versions', 'is_baseline',
               existing_type=sa.BOOLEAN(),
               comment='Is this the baseline for A/B comparison',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('trending_topics', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment='Category (tech, finance, health, etc.)',
               existing_nullable=True)
    op.alter_column('trending_topics', 'trend_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Relative popularity score (0-100)',
               existing_nullable=False)
    op.alter_column('trending_topics', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='google_trends or youtube_trending',
               existing_nullable=False)
    op.alter_column('trending_topics', 'region',
               existing_type=sa.VARCHAR(length=10),
               comment='Country code (US, IN, GB, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'US'::character varying"))
    op.alter_column('trending_topics', 'related_queries',
               existing_type=sa.TEXT(),
               comment='JSON string of related search queries',
               existing_nullable=True)
    op.alter_column('trending_topics', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this trend data becomes stale',
               existing_nullable=False)
    op.drop_index(op.f('ix_trending_category'), table_name='trending_topics')
    op.create_index(op.f('ix_trending_topics_category'), 'trending_topics', ['category'], unique=False)
    op.alter_column('video_analytics', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               comment='FK to video_projects.id',
               existing_nullable=False)
    op.alter_column('video_analytics', 'youtube_video_id',
               existing_type=sa.VARCHAR(length=64),
               comment='YouTube video ID',
               existing_nullable=False)
    op.alter_column('video_analytics', 'snapshot_date',
               existing_type=sa.DATE(),
               comment='Date of this metrics snapshot',
               existing_nullable=False)
    op.alter_column('video_analytics', 'click_through_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='CTR percentage (0-100)',
               existing_nullable=True)
    op.alter_column('video_analytics', 'average_view_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Retention percentage',
               existing_nullable=True)
    op.alter_column('video_analytics', 'collected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When we fetched this data',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('video_projects', 'last_completed_step',
               existing_type=sa.VARCHAR(length=50),
               comment='Last successfully completed pipeline step (for resuming)',
               existing_nullable=True)
    op.alter_column('video_projects', 'artifacts_available',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON object tracking which intermediate artifacts exist',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('video_projects', 'ai_video_provider',
               existing_type=sa.VARCHAR(length=20),
               comment='AI video provider used: runway, stability, kling',
               existing_comment='AI video provider: runway, stability, kling',
               existing_nullable=True)
    op.alter_column('video_projects', 'prompt_version_id',
               existing_type=sa.VARCHAR(length=36),
               comment='FK to prompt_versions.id — which prompt version generated this script',
               existing_comment='FK to prompt_versions.id',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Re-add the duplicate lowercase enum value
    op.execute("ALTER TYPE video_status ADD VALUE IF NOT EXISTS 'scene_splitting'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_projects', 'prompt_version_id',
               existing_type=sa.VARCHAR(length=36),
               comment='FK to prompt_versions.id',
               existing_comment='FK to prompt_versions.id — which prompt version generated this script',
               existing_nullable=True)
    op.alter_column('video_projects', 'ai_video_provider',
               existing_type=sa.VARCHAR(length=20),
               comment='AI video provider: runway, stability, kling',
               existing_comment='AI video provider used: runway, stability, kling',
               existing_nullable=True)
    op.alter_column('video_projects', 'artifacts_available',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON object tracking which intermediate artifacts exist',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('video_projects', 'last_completed_step',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Last successfully completed pipeline step (for resuming)',
               existing_nullable=True)
    op.alter_column('video_analytics', 'collected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When we fetched this data',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('video_analytics', 'average_view_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Retention percentage',
               existing_nullable=True)
    op.alter_column('video_analytics', 'click_through_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='CTR percentage (0-100)',
               existing_nullable=True)
    op.alter_column('video_analytics', 'snapshot_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date of this metrics snapshot',
               existing_nullable=False)
    op.alter_column('video_analytics', 'youtube_video_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='YouTube video ID',
               existing_nullable=False)
    op.alter_column('video_analytics', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='FK to video_projects.id',
               existing_nullable=False)
    op.drop_index(op.f('ix_trending_topics_category'), table_name='trending_topics')
    op.create_index(op.f('ix_trending_category'), 'trending_topics', ['category'], unique=False)
    op.alter_column('trending_topics', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this trend data becomes stale',
               existing_nullable=False)
    op.alter_column('trending_topics', 'related_queries',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON string of related search queries',
               existing_nullable=True)
    op.alter_column('trending_topics', 'region',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Country code (US, IN, GB, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'US'::character varying"))
    op.alter_column('trending_topics', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='google_trends or youtube_trending',
               existing_nullable=False)
    op.alter_column('trending_topics', 'trend_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Relative popularity score (0-100)',
               existing_nullable=False)
    op.alter_column('trending_topics', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Category (tech, finance, health, etc.)',
               existing_nullable=True)
    op.alter_column('prompt_versions', 'is_baseline',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Is this the baseline for A/B comparison',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('prompt_versions', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Currently in use (only one active at a time)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('prompt_versions', 'variables',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON default variable values',
               existing_nullable=True)
    op.alter_column('prompt_versions', 'template',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Full prompt template with {placeholders}',
               existing_nullable=False)
    op.alter_column('prompt_versions', 'version_label',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='v1, v2.1, experiment-hooks-q3',
               existing_nullable=False)
    op.alter_column('performance_patterns', 'supporting_evidence',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON list of project_ids and their stats',
               existing_nullable=False)
    op.alter_column('performance_patterns', 'avg_retention',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Average retention percentage',
               existing_nullable=True)
    op.alter_column('performance_patterns', 'avg_views',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Average views for videos matching this pattern',
               existing_nullable=False)
    op.alter_column('performance_patterns', 'sample_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of videos this pattern is based on',
               existing_nullable=False)
    op.alter_column('performance_patterns', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='0.0 to 1.0',
               existing_nullable=False)
    op.alter_column('performance_patterns', 'pattern_data',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON structured pattern details',
               existing_nullable=False)
    op.alter_column('performance_patterns', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Human-readable pattern description',
               existing_nullable=False)
    op.alter_column('performance_patterns', 'pattern_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='hook_style, topic, cta, script_structure, length',
               existing_nullable=False)
    # ### end Alembic commands ###
