"""add api_keys table

Revision ID: f19ac12d9af5
Revises: a7e8f2d3b4c5
Create Date: 2026-03-04 09:20:16.554693
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19ac12d9af5'
down_revision: Union[str, None] = 'a7e8f2d3b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('key', sa.String(length=100), nullable=False, comment='API key for authentication'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Descriptive name for this key'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this key is currently active'),
    sa.Column('rate_limit', sa.Integer(), nullable=False, comment='Maximum requests allowed per hour'),
    sa.Column('requests_this_hour', sa.Integer(), nullable=False, comment='Requests made in current hour'),
    sa.Column('rate_limit_reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When rate limit counter resets'),
    sa.Column('total_requests', sa.Integer(), nullable=False, comment='Total requests made with this key'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Last time this key was used'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
